name: coastal_fim_vis
channels:
  - conda-forge
  - defaults

channel-priority: strict

dependencies:
  - python=3.12
  - pip
  - pytest 
  - gdal
  - geopandas
  - rasterio
  - rioxarray
  - shapely
  - fiona
  - pyproj
  - folium
  - leafmap
  - ipyleaflet
  - whitebox 
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - xarray
  - dask
  - distributed
  - statsmodels
  - numba 
  - duckdb
  - python-duckdb
  - ibis-framework
  - pyarrow       
  - zarr
  - h5py
  - netcdf4
  - fsspec
  - s3fs          
  - requests
  - jupyterlab
  - notebook
  - ipywidgets
  - ipykernel
  - matplotlib
  - seaborn
  - bokeh
  - plotly
  - tqdm          
  - beautifulsoup4 
  - boto3         
  - botocore      
  - colorama      
  - click         
  - pyyaml        